Enhance code analysis step in Python workflow
Add commands to check current directory and list docs contents.

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -123,6 +123,9 @@ jobs:
       - name: Code analysis
         continue-on-error: true
         run: |
+          pwd
+          ls -la docs
+          test -f docs/QRB_flake8_error.md && echo "FOUND" || echo "MISSING"
 
           echo "##   Flake8" >> "$REPORT"
           echo "" >> "$REPORT"
